site_name: pyetp & rddms-io
site_description: Documentation for pyetp and rddms-io
# TODO: Set `site_url`

repo_name: "equinor/pyetp"
repo_url: "https://github.com/equinor/pyetp"

nav:
  - Introduction: index.md
  - Tutorials:
    - tutorials/index.md
    - tutorials/set_up_regular_surface.md
    - tutorials/using_the_rddms_client.md
  - API:
    - RDDMS Client: api/rddms_client.md
    - ETP v1.2 Client:
      - api/etp_client/index.md
      - api/etp_client/etp_objects.md
    - RESQML objects:
      - api/resqml_objects/serializers.md
      - v201:
        - api/resqml_objects/v201/index.md

plugins:
  - mkdocstrings:
      handlers:
          python:
              paths: [src]
              options:
                  docstring_style: numpy
                  docstring_section_style: spacy
                  line_length: 88
                  unwrap_annotated: true
                  heading_level: 3
                  inherited_members: true
                  members_order: source
                  merge_init_into_class: true
                  separate_signature: true
                  show_root_heading: true
                  show_if_no_docstring: true
                  show_signature_annotations: true
                  show_symbol_type_heading: true
                  show_symbol_type_toc: true
                  signature_crossrefs: true

theme:
  name: material
  language: "en"
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.indexes
    - content.code.copy


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
